### PR TITLE
refactor print_

### PR DESCRIPTION
**Pull request by alikarani**
LGTM @ammaratef45 
Issue [(https://github.com/ammaratef45/dart_stack/issues/8)]

### CODE REVIEW

**Review by ammaratef45 — APPROVED** [review]
@alikarani Sounds good, thanks

**Comment by alikarani** [comment]
@ammaratef45  Can you add "hacktoberfest" topic to their repository, so it could be counted.
image

**Comment by ammaratef45** [comment]
I'll give it a look and let you know, I'll put it on top of my todo list

**Comment by ammaratef45** [comment]
@alikarani check it now!

**Comment by alikarani** [comment]
thanks :)  @ammaratef45

**Pull request merged**
